[[constraint]]
  branch = "master"
  name = "github.com/BurntSushi/toml"

[[constraint]]
  branch = "master"
  name = "github.com/briandowns/spinner"

[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "1.1.0"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.5.0"

[[constraint]]
  branch = "master"
  name = "github.com/inconshreveable/mousetrap"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  branch = "master"
  name = "github.com/pkg/errors"

[[constraint]]
  name = "github.com/pmezard/go-difflib"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  branch = "master"
  name = "github.com/stretchr/testify"

[[constraint]]
  version = "v4.0.0-rc13"
  name = "gopkg.in/src-d/go-git.v4"
